language: node_js
node_js:
  - stable
branches:
  only:
    - master

cache:
  directories:
    - node_modules
install:
  - pip install awscli --user

script:
  # pull from Outputs[] where OutputKey = outputbucket or all expoerts for jonessite-bucket
  - STACK_NAME=jonessite
  - BUCKET=$(aws cloudformation --region us-east-1 describe-stacks --stack-name ${STACK_NAME} --query 'Stacks[0].Outputs[?OutputKey==`outputbucket`].OutputValue' --output text)
  - OAI=$(aws cloudformation --region us-east-1 describe-stacks --stack-name ${STACK_NAME} --query 'Stacks[0].Outputs[?OutputKey==`outputoai`].OutputValue' --output text)
  #- BUCKET=$(aws cloudformation --region us-east-1 describe-stacks --stack-name jonessite | jq '.Stacks[0].Outputs[0].OutputValue')
  - echo $BUCKET
  - aws sts get-caller-identity
  - npm run build
  #- aws s3 sync ./build s3://${BUCKET}/ --delete --grants read=id=${OAI}
  - aws s3 sync ./build s3://${BUCKET}/ --delete

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master


# deploy:
#   provider: s3
#   bucket:
#   on:
#     branch: master


notifications:
  email:
    on_failure: always
