language: node_js
node_js:
  - stable
branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - aws sts get-caller-identity
  - npm run build
  #- aws s3 sync

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master


# deploy:
#   provider: s3
#   bucket:
#   on:
#     branch: master


notifications:
  email:
    on_failure: always
